# 配置文件版本号,请勿修改
version: 1.00

groups:
  - "0000000000"


# 数据库配置
mysql:
  host: localhost
  port: 3306
  user: root
  password: ""
  database: database
  # 保存请求权限物品数据表，不存在则创建表
  item_table: ItemPermission
  # 保存请求权限数据的表，不存在则创建表
  permission_table: RequestPermission
  # 连接参数
  params: "?useSSL=false"